//==============================================================================
// tb_multi_agent.sv
//
// Example testbench with TWO independent AXI agents connected to different
// ports on the same DUT:
//
//   • hp_agent  – 32-bit data, 32-bit address  (high-performance port)
//   • gp_agent  – 32-bit data, 32-bit address, 4-bit ID (general-purpose port)
//
// The same pattern scales to any number of buses with different widths.
//==============================================================================

`timescale 1ns/1ps

import uvm_pkg::*;
`include "uvm_macros.svh"

import axi_vip_pkg::*;
import axi_vip_master_pkg::*;      // generated by Vivado IP catalog
import axi_uvm_pkg::*;

// axi_params.sv and axi_if are compiled before this file (not inside a package)

module tb_multi_agent();

    //==========================================================================
    // 1. Declare one axi_params specialisation per bus configuration
    //==========================================================================

    // HP port: 32-bit addr, 64-bit data, 1-bit ID
    typedef axi_params #(.ADDR_W(32), .DATA_W(64), .ID_W(1), .USER_W(1))
        hp_params_t;

    // GP port: 32-bit addr, 32-bit data, 4-bit ID
    typedef axi_params #(.ADDR_W(32), .DATA_W(32), .ID_W(4), .USER_W(1))
        gp_params_t;

    // Convenience item/seq typedefs (optional but recommended)
    typedef axi_seq_item       #(hp_params_t)  hp_item_t;
    typedef axi_seq_item       #(gp_params_t)  gp_item_t;
    typedef axi_write_read_seq #(hp_params_t)  hp_wr_seq_t;
    typedef axi_rand_seq       #(gp_params_t)  gp_rand_seq_t;

    //==========================================================================
    // 2. Clocks and resets
    //==========================================================================
    bit aclk;
    always #10 aclk = ~aclk;   // 50 MHz

    bit aresetn;
    initial begin
        aresetn = 0;
        repeat (20) @(negedge aclk);
        aresetn = 1;
    end

    //==========================================================================
    // 3. AXI signal buses (one set of flat wires per port)
    //==========================================================================

    // ── HP bus (64-bit data) ──────────────────────────────────────────────
    logic [31:0]  hp_awaddr;  logic [7:0]  hp_awlen;  logic [2:0]  hp_awsize;
    logic [1:0]   hp_awburst; logic        hp_awlock;  logic [3:0]  hp_awcache;
    logic [2:0]   hp_awprot;  logic [3:0]  hp_awregion; logic [3:0] hp_awqos;
    logic         hp_awvalid; logic        hp_awready;
    logic [63:0]  hp_wdata;   logic [7:0]  hp_wstrb;  logic        hp_wlast;
    logic         hp_wvalid;  logic        hp_wready;
    logic [1:0]   hp_bresp;   logic        hp_bvalid;  logic        hp_bready;
    logic [31:0]  hp_araddr;  logic [7:0]  hp_arlen;  logic [2:0]  hp_arsize;
    logic [1:0]   hp_arburst; logic        hp_arlock;  logic [3:0]  hp_arcache;
    logic [2:0]   hp_arprot;  logic [3:0]  hp_arregion; logic [3:0] hp_arqos;
    logic         hp_arvalid; logic        hp_arready;
    logic [63:0]  hp_rdata;   logic [1:0]  hp_rresp;  logic        hp_rlast;
    logic         hp_rvalid;  logic        hp_rready;

    // ── GP bus (32-bit data, 4-bit ID) ───────────────────────────────────
    logic [3:0]   gp_awid;    logic [31:0] gp_awaddr; logic [7:0]  gp_awlen;
    logic [2:0]   gp_awsize;  logic [1:0]  gp_awburst; logic       gp_awlock;
    logic [3:0]   gp_awcache; logic [2:0]  gp_awprot; logic [3:0]  gp_awregion;
    logic [3:0]   gp_awqos;   logic        gp_awvalid; logic        gp_awready;
    logic [31:0]  gp_wdata;   logic [3:0]  gp_wstrb;  logic        gp_wlast;
    logic         gp_wvalid;  logic        gp_wready;
    logic [3:0]   gp_bid;     logic [1:0]  gp_bresp;  logic        gp_bvalid;
    logic         gp_bready;
    logic [3:0]   gp_arid;    logic [31:0] gp_araddr; logic [7:0]  gp_arlen;
    logic [2:0]   gp_arsize;  logic [1:0]  gp_arburst; logic       gp_arlock;
    logic [3:0]   gp_arcache; logic [2:0]  gp_arprot; logic [3:0]  gp_arregion;
    logic [3:0]   gp_arqos;   logic        gp_arvalid; logic        gp_arready;
    logic [3:0]   gp_rid;     logic [31:0] gp_rdata;  logic [1:0]  gp_rresp;
    logic         gp_rlast;   logic        gp_rvalid;  logic        gp_rready;

    //==========================================================================
    // 4. Virtual interfaces – one per bus, connected to flat wires
    //==========================================================================
    axi_if #(.ADDR_W(32), .DATA_W(64), .ID_W(1), .USER_W(1))
        hp_if (.aclk(aclk), .aresetn(aresetn));

    axi_if #(.ADDR_W(32), .DATA_W(32), .ID_W(4), .USER_W(1))
        gp_if (.aclk(aclk), .aresetn(aresetn));

    // HP interface ↔ flat wires
    assign hp_if.awaddr = hp_awaddr; assign hp_if.awlen  = hp_awlen;
    assign hp_if.awsize = hp_awsize; assign hp_if.awburst = hp_awburst;
    assign hp_if.awlock = hp_awlock; assign hp_if.awcache = hp_awcache;
    assign hp_if.awprot = hp_awprot; assign hp_if.awregion= hp_awregion;
    assign hp_if.awqos  = hp_awqos;  assign hp_if.awvalid = hp_awvalid;
    assign hp_if.awready= hp_awready;
    assign hp_if.wdata  = hp_wdata;  assign hp_if.wstrb  = hp_wstrb;
    assign hp_if.wlast  = hp_wlast;  assign hp_if.wvalid = hp_wvalid;
    assign hp_if.wready = hp_wready;
    assign hp_if.bresp  = hp_bresp;  assign hp_if.bvalid = hp_bvalid;
    assign hp_if.bready = hp_bready;
    assign hp_if.araddr = hp_araddr; assign hp_if.arlen  = hp_arlen;
    assign hp_if.arsize = hp_arsize; assign hp_if.arburst= hp_arburst;
    assign hp_if.arlock = hp_arlock; assign hp_if.arcache= hp_arcache;
    assign hp_if.arprot = hp_arprot; assign hp_if.arregion=hp_arregion;
    assign hp_if.arqos  = hp_arqos;  assign hp_if.arvalid= hp_arvalid;
    assign hp_if.arready= hp_arready;
    assign hp_if.rdata  = hp_rdata;  assign hp_if.rresp  = hp_rresp;
    assign hp_if.rlast  = hp_rlast;  assign hp_if.rvalid = hp_rvalid;
    assign hp_if.rready = hp_rready;

    // GP interface ↔ flat wires
    assign gp_if.awid   = gp_awid;   assign gp_if.awaddr = gp_awaddr;
    assign gp_if.awlen  = gp_awlen;  assign gp_if.awsize = gp_awsize;
    assign gp_if.awburst= gp_awburst;assign gp_if.awlock = gp_awlock;
    assign gp_if.awcache= gp_awcache;assign gp_if.awprot = gp_awprot;
    assign gp_if.awregion=gp_awregion;assign gp_if.awqos = gp_awqos;
    assign gp_if.awvalid= gp_awvalid;assign gp_if.awready= gp_awready;
    assign gp_if.wdata  = gp_wdata;  assign gp_if.wstrb  = gp_wstrb;
    assign gp_if.wlast  = gp_wlast;  assign gp_if.wvalid = gp_wvalid;
    assign gp_if.wready = gp_wready;
    assign gp_if.bid    = gp_bid;    assign gp_if.bresp  = gp_bresp;
    assign gp_if.bvalid = gp_bvalid; assign gp_if.bready = gp_bready;
    assign gp_if.arid   = gp_arid;   assign gp_if.araddr = gp_araddr;
    assign gp_if.arlen  = gp_arlen;  assign gp_if.arsize = gp_arsize;
    assign gp_if.arburst= gp_arburst;assign gp_if.arlock = gp_arlock;
    assign gp_if.arcache= gp_arcache;assign gp_if.arprot = gp_arprot;
    assign gp_if.arregion=gp_arregion;assign gp_if.arqos = gp_arqos;
    assign gp_if.arvalid= gp_arvalid;assign gp_if.arready= gp_arready;
    assign gp_if.rid    = gp_rid;    assign gp_if.rdata  = gp_rdata;
    assign gp_if.rresp  = gp_rresp;  assign gp_if.rlast  = gp_rlast;
    assign gp_if.rvalid = gp_rvalid; assign gp_if.rready = gp_rready;

    //==========================================================================
    // 5. Xilinx VIP masters (one per bus, generated by IP catalog)
    //==========================================================================
    axi_vip_master_hp hp_vip_master (
        .aclk(aclk), .aresetn(aresetn),
        .m_axi_awaddr(hp_awaddr), .m_axi_awlen(hp_awlen),
        .m_axi_awsize(hp_awsize), .m_axi_awburst(hp_awburst),
        .m_axi_awlock(hp_awlock), .m_axi_awcache(hp_awcache),
        .m_axi_awprot(hp_awprot), .m_axi_awregion(hp_awregion),
        .m_axi_awqos(hp_awqos),   .m_axi_awvalid(hp_awvalid),
        .m_axi_awready(hp_awready),
        .m_axi_wdata(hp_wdata),   .m_axi_wstrb(hp_wstrb),
        .m_axi_wlast(hp_wlast),   .m_axi_wvalid(hp_wvalid),
        .m_axi_wready(hp_wready),
        .m_axi_bresp(hp_bresp),   .m_axi_bvalid(hp_bvalid),
        .m_axi_bready(hp_bready),
        .m_axi_araddr(hp_araddr), .m_axi_arlen(hp_arlen),
        .m_axi_arsize(hp_arsize), .m_axi_arburst(hp_arburst),
        .m_axi_arlock(hp_arlock), .m_axi_arcache(hp_arcache),
        .m_axi_arprot(hp_arprot), .m_axi_arregion(hp_arregion),
        .m_axi_arqos(hp_arqos),   .m_axi_arvalid(hp_arvalid),
        .m_axi_arready(hp_arready),
        .m_axi_rdata(hp_rdata),   .m_axi_rresp(hp_rresp),
        .m_axi_rlast(hp_rlast),   .m_axi_rvalid(hp_rvalid),
        .m_axi_rready(hp_rready)
    );

    axi_vip_master_gp gp_vip_master (
        .aclk(aclk), .aresetn(aresetn),
        .m_axi_awid(gp_awid),     .m_axi_awaddr(gp_awaddr),
        .m_axi_awlen(gp_awlen),   .m_axi_awsize(gp_awsize),
        .m_axi_awburst(gp_awburst),.m_axi_awlock(gp_awlock),
        .m_axi_awcache(gp_awcache),.m_axi_awprot(gp_awprot),
        .m_axi_awregion(gp_awregion),.m_axi_awqos(gp_awqos),
        .m_axi_awvalid(gp_awvalid),.m_axi_awready(gp_awready),
        .m_axi_wdata(gp_wdata),   .m_axi_wstrb(gp_wstrb),
        .m_axi_wlast(gp_wlast),   .m_axi_wvalid(gp_wvalid),
        .m_axi_wready(gp_wready),
        .m_axi_bid(gp_bid),       .m_axi_bresp(gp_bresp),
        .m_axi_bvalid(gp_bvalid), .m_axi_bready(gp_bready),
        .m_axi_arid(gp_arid),     .m_axi_araddr(gp_araddr),
        .m_axi_arlen(gp_arlen),   .m_axi_arsize(gp_arsize),
        .m_axi_arburst(gp_arburst),.m_axi_arlock(gp_arlock),
        .m_axi_arcache(gp_arcache),.m_axi_arprot(gp_arprot),
        .m_axi_arregion(gp_arregion),.m_axi_arqos(gp_arqos),
        .m_axi_arvalid(gp_arvalid),.m_axi_arready(gp_arready),
        .m_axi_rid(gp_rid),       .m_axi_rdata(gp_rdata),
        .m_axi_rresp(gp_rresp),   .m_axi_rlast(gp_rlast),
        .m_axi_rvalid(gp_rvalid), .m_axi_rready(gp_rready)
    );

    //==========================================================================
    // 6. DUT (your multi-port device under test)
    //==========================================================================
    // my_dut dut (
    //     .aclk        (aclk),   .aresetn      (aresetn),
    //     // HP port
    //     .hp_awaddr   (hp_awaddr), ...
    //     // GP port
    //     .gp_awid     (gp_awid),   ...
    // );

    //==========================================================================
    // 7. UVM kickoff
    //==========================================================================
    initial begin : uvm_start
        axi_vip_master_mst_t hp_vip_h, gp_vip_h;

        // ── Create and start both Xilinx VIP masters ──
        hp_vip_h = new("hp_vip_h", hp_vip_master.inst.IF);
        hp_vip_h.start_master();

        gp_vip_h = new("gp_vip_h", gp_vip_master.inst.IF);
        gp_vip_h.start_master();

        // ── Publish virtual interfaces to config_db ──
        // Keys match the paths used in the UVM agent's monitor build_phase.
        uvm_config_db #(hp_params_t::vif_t)::set(
            null, "uvm_test_top.env.hp_agent.*", "vif", hp_if);
        uvm_config_db #(gp_params_t::vif_t)::set(
            null, "uvm_test_top.env.gp_agent.*", "vif", gp_if);

        // ── Publish VIP handles to config_db ──
        uvm_config_db #(axi_vip_master_mst_t)::set(
            null, "uvm_test_top.env.hp_agent", "vip_agent", hp_vip_h);
        uvm_config_db #(axi_vip_master_mst_t)::set(
            null, "uvm_test_top.env.gp_agent", "vip_agent", gp_vip_h);

        run_test();
    end

endmodule : tb_multi_agent


//==============================================================================
// axi_multi_env
// Environment that owns one agent per bus.
//==============================================================================
class axi_multi_env extends uvm_env;
    `uvm_component_utils(axi_multi_env)

    axi_agent #(hp_params_t) hp_agent;
    axi_agent #(gp_params_t) gp_agent;

    function new(string name, uvm_component parent);
        super.new(name, parent);
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        hp_agent = axi_agent #(hp_params_t)::type_id::create("hp_agent", this);
        gp_agent = axi_agent #(gp_params_t)::type_id::create("gp_agent", this);
    endfunction

endclass : axi_multi_env


//==============================================================================
// axi_multi_base_test
//==============================================================================
class axi_multi_base_test extends uvm_test;
    `uvm_component_utils(axi_multi_base_test)

    axi_multi_env env;

    function new(string name, uvm_component parent);
        super.new(name, parent);
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        env = axi_multi_env::type_id::create("env", this);
    endfunction

    task run_phase(uvm_phase phase);
        phase.raise_objection(this);
        @(posedge tb_multi_agent.aresetn);
        repeat(3) @(posedge tb_multi_agent.aclk);
        run_sequences();
        phase.drop_objection(this);
    endtask

    virtual task run_sequences(); endtask

endclass : axi_multi_base_test


//==============================================================================
// axi_multi_test
// Drives HP and GP ports in parallel using fork/join.
//==============================================================================
class axi_multi_test extends axi_multi_base_test;
    `uvm_component_utils(axi_multi_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
    endfunction

    virtual task run_sequences();
        fork
            // ── HP port: directed write-then-read ──────────────────────────
            begin
                hp_wr_seq_t seq = hp_wr_seq_t::type_id::create("hp_seq");
                seq.addr       = 32'h0000_1000;
                seq.len        = 3;               // 4 beats × 8 bytes = 32 B
                seq.size       = hp_params_t::AXI_SIZE_8B;
                seq.burst      = hp_params_t::AXI_BURST_INCR;
                seq.check_data = 1;
                seq.start(env.hp_agent.sequencer);
            end

            // ── GP port: 10 randomised transactions ────────────────────────
            begin
                gp_rand_seq_t seq = gp_rand_seq_t::type_id::create("gp_seq");
                seq.num_txns = 10;
                seq.start(env.gp_agent.sequencer);
            end
        join

        `uvm_info("TEST", "Both ports complete", UVM_MEDIUM)
    endtask

endclass : axi_multi_test
